{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Clinical_HIPster\",\"Clinical_Caregiver\",\"LLL_Hipster\",\"LLL_Caregiver\",\"Online_Caregiver\",\"Online_HIPster\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.127.1327.0 (24.03)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_712351c3-b871-49b0-8048-9f431512223a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d4f1b9e6-68d6-4ad5-a260-8e2e3ec1ab1d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "8a29b581-d0fe-4cbc-968c-421ae2230490",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "2bf3ebe9-876d-4495-8ac4-57f8d4436166",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "95cbdb9b-7156-4c5b-a9ff-69ce92d57d32",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d9b05f9a-a936-4fc4-bade-c86871ff6b36",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f8dff26e-da8d-40e9-a1cc-fe86a93b6626",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "beaafcb0-9050-4bed-9161-7b74de9ea322",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7e9d6e18-6121-4b8c-8216-04f4f1f8bf4b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9c613276-1134-4d04-b6a9-94ae8ae640ff",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2eeea692-f714-415b-8c1e-fc6e5b6decf9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "21d7e51e-4324-48d1-83d8-66a79a09ad93",
                "ordinal": 3
              }
            ],
            "lineageTag": "6f372372-5106-4c5e-a60b-1cc837664d28"
          }
        ],
        "isPrivate": true,
        "lineageTag": "d5f032c5-5031-465f-9c64-f3622b185606",
        "partitions": [
          {
            "name": "DateTableTemplate_712351c3-b871-49b0-8048-9f431512223a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Clinical_HIPster",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae9ff398-fc70-41a6-85b6-e41923ab4190",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Start time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55213796-19c7-4466-a95a-b0096394b319",
            "sourceColumn": "Start time",
            "summarizeBy": "none"
          },
          {
            "name": "Completion time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "caa81806-b1cc-47ee-8141-fd19ae9614ac",
            "sourceColumn": "Completion time",
            "summarizeBy": "none"
          },
          {
            "name": "HIPster name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d41517da-2e6f-445c-bae4-c3c81692f3bc",
            "sourceColumn": "HIPster name",
            "summarizeBy": "none"
          },
          {
            "name": "Gender: ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d7d2605-4403-4a18-8d50-f8dee31873b5",
            "sourceColumn": "Gender: ",
            "summarizeBy": "none"
          },
          {
            "name": "Which therapy do you attend? (check all that apply)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a0fe821-5b0f-4a31-953c-7f5931a75416",
            "sourceColumn": "Which therapy do you attend? (check all that apply)",
            "summarizeBy": "none"
          },
          {
            "name": "Do you like therapy at MP?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e99438b-7e37-405a-b263-c44e9929116a",
            "sourceColumn": "Do you like therapy at MP?",
            "summarizeBy": "none"
          },
          {
            "name": "Did you choose what you're working on in therapy?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22c2f158-7ea0-4a59-9ba2-246ec6fcd26b",
            "sourceColumn": "Did you choose what you're working on in therapy?",
            "summarizeBy": "none"
          },
          {
            "name": "Does your therapist help you learn new skills?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae8c475d-f8ef-431d-9d8c-4b9a02e12586",
            "sourceColumn": "Does your therapist help you learn new skills?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you use new skills outside of MP (at home, work, or in the community)?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ac187bb-b136-4ecc-877d-aef6f8260f74",
            "sourceColumn": "Do you use new skills outside of MP (at home, work, or in the community)?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you learned to share your wants and needs?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa8e739a-8455-46dd-872f-4802560f0f2a",
            "sourceColumn": "Have you learned to share your wants and needs?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you learned how to communicate with your friends and family?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a23609c-ca97-4022-af33-9e9660921628",
            "sourceColumn": "Have you learned how to communicate with your friends and family?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you learned how to manage your emotions?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46ab2d1c-1555-43e8-94d4-df73b9234310",
            "sourceColumn": "Have you learned how to manage your emotions?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you learned how to ask for help when needed?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17245a7e-e094-4fa1-bd59-d2dd9a798fa3",
            "sourceColumn": "Have you learned how to ask for help when needed?",
            "summarizeBy": "none"
          },
          {
            "name": "What skill have you learned in therapy that has helped you the most?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87b27637-7946-41b0-bdf5-6ef08d6c134c",
            "sourceColumn": "What skill have you learned in therapy that has helped you the most?",
            "summarizeBy": "none"
          },
          {
            "name": "What other skills would you like to learn in therapy?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e2f1c5e-4ad5-4a08-bade-e7233e8aa519",
            "sourceColumn": "What other skills would you like to learn in therapy?",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "550674d6-d352-415c-87b8-3624b4e94bdf",
        "partitions": [
          {
            "name": "Clinical_HIPster",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://github.com/seancairns14/UTDMyPossibilities/raw/main/Sources/Clinical/Clinical%20Services%20HIPster%20Survey%20(1-104).xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"ID\", Int64.Type}, {\"Start time\", type datetime}, {\"Completion time\", type datetime}, {\"Email\", type text}, {\"Name\", type any}, {\"Last modified time\", type any}, {\"HIPster name\", type text}, {\"Gender: \", type text}, {\"Which therapy do you attend? (check all that apply)\", type text}, {\"Do you like therapy at MP?\", type text}, {\"Did you choose what you're working on in therapy?\", type text}, {\"Does your therapist help you learn new skills?\", type text}, {\"Do you use new skills outside of MP (at home, work, or in the community)?\", type text}, {\"Have you learned to share your wants and needs?\", type text}, {\"Have you learned how to communicate with your friends and family?\", type text}, {\"Have you learned how to manage your emotions?\", type text}, {\"Have you learned how to ask for help when needed?\", type text}, {\"What skill have you learned in therapy that has helped you the most?\", type text}, {\"What other skills would you like to learn in therapy?\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Sometimes\",\"Yes\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"Name\", \"Last modified time\", \"HIPster name\", \"Gender: \", \"Which therapy do you attend? (check all that apply)\", \"Do you like therapy at MP?\", \"Did you choose what you're working on in therapy?\", \"Does your therapist help you learn new skills?\", \"Do you use new skills outside of MP (at home, work, or in the community)?\", \"Have you learned to share your wants and needs?\", \"Have you learned how to communicate with your friends and family?\", \"Have you learned how to manage your emotions?\", \"Have you learned how to ask for help when needed?\", \"What skill have you learned in therapy that has helped you the most?\", \"What other skills would you like to learn in therapy?\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value\",{\"Email\", \"Name\", \"Last modified time\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Clinical_Caregiver",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1a62837-7127-4526-9118-1a024a6e2628",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Start time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4be0a7f1-7ace-4651-90cb-c3e0668dcd96",
            "sourceColumn": "Start time",
            "summarizeBy": "none"
          },
          {
            "name": "Completion time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a28e4380-cb4b-47f3-864b-3fca6d89bb67",
            "sourceColumn": "Completion time",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster's Gender:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f914557-3d1c-4299-a04b-72a709e7ca2d",
            "sourceColumn": "My HIPster's Gender:",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Therapy Received (may select more than one):",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9711bac5-b7ce-4934-906f-a519d5149bce",
            "sourceColumn": "Type of Therapy Received (may select more than one):",
            "summarizeBy": "none"
          },
          {
            "name": "I am satisfied with the therapy services at MP.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5a9e33a-88ac-48be-b001-347d8adff296",
            "sourceColumn": "I am satisfied with the therapy services at MP.",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster's daily living skills have improved since starting therapy at MP.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ad26c9c-044c-4604-bf02-9ef14457cbbf",
            "sourceColumn": "My HIPster's daily living skills have improved since starting therapy at MP.",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster's social skills have improved since starting therapy at MP.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f924efeb-037c-4c9c-b47f-6febce805f04",
            "sourceColumn": "My HIPster's social skills have improved since starting therapy at MP.",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster's communication skills have improved since starting therapy at MP.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b93834e1-144f-468c-b194-ff82eca3845a",
            "sourceColumn": "My HIPster's communication skills have improved since starting therapy at MP.",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster is more independent since starting therapy services at MP.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45e0a1fb-c893-4051-ae43-6b9cf5c67378",
            "sourceColumn": "My HIPster is more independent since starting therapy services at MP.",
            "summarizeBy": "none"
          },
          {
            "name": "The therapy program is addressing the specific needs of my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "139f65ad-552a-4f96-84a0-844f0185b06a",
            "sourceColumn": "The therapy program is addressing the specific needs of my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "I would like to see additional therapy services added to the program.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc053bf8-8125-431d-8ae4-cdfab191160b",
            "sourceColumn": "I would like to see additional therapy services added to the program.",
            "summarizeBy": "none"
          },
          {
            "name": "Therapy staff is flexible and adapts to accommodate HIPsters' needs.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "faf08a40-44a3-49e0-9450-971889e08961",
            "sourceColumn": "Therapy staff is flexible and adapts to accommodate HIPsters' needs.",
            "summarizeBy": "none"
          },
          {
            "name": "Therapy staff communicates effectively regarding therapy goals and schedules.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4296824-7efe-4830-b3bf-ed5689c98599",
            "sourceColumn": "Therapy staff communicates effectively regarding therapy goals and schedules.",
            "summarizeBy": "none"
          },
          {
            "name": "The cost of the therapy program is prohibitive, so my HIPster is not receiving as much therapy as they need.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b89476e7-c140-4db9-bf8a-1e9684579da1",
            "sourceColumn": "The cost of the therapy program is prohibitive, so my HIPster is not receiving as much therapy as they need.",
            "summarizeBy": "none"
          },
          {
            "name": "Is there anything you would like to share with the Clinical Services Department?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b363b33-d589-42e0-8ef2-0ece5f51b70e",
            "sourceColumn": "Is there anything you would like to share with the Clinical Services Department?",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) HIPster's name:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3eb1d3a7-aa2a-4824-8a8a-7d0126a5e680",
            "sourceColumn": "(Optional) HIPster's name:",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) Your name:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "493e076c-ca36-406f-9bad-8c7e1da2b926",
            "sourceColumn": "(Optional) Your name:",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) Your email address:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29c0cced-652b-4d92-8aa2-91ebe35d8438",
            "sourceColumn": "(Optional) Your email address:",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "57bf8332-ff25-4f8a-be6a-34eb737f0ce8",
        "partitions": [
          {
            "name": "Clinical_Caregiver",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://github.com/seancairns14/UTDMyPossibilities/raw/main/Sources/Clinical/Clinical%20ServicesCaregiver%C2%A0Survey(1-43).xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"ID\", Int64.Type}, {\"Start time\", type datetime}, {\"Completion time\", type datetime}, {\"Email\", type text}, {\"Name\", type any}, {\"Last modified time\", type any}, {\"My HIPster's Gender:\", type text}, {\"Type of Therapy Received (may select more than one):\", type text}, {\"I am satisfied with the therapy services at MP.\", type text}, {\"My HIPster's daily living skills have improved since starting therapy at MP.\", type text}, {\"My HIPster's social skills have improved since starting therapy at MP.\", type text}, {\"My HIPster's communication skills have improved since starting therapy at MP.\", type text}, {\"My HIPster is more independent since starting therapy services at MP.\", type text}, {\"The therapy program is addressing the specific needs of my HIPster.\", type text}, {\"I would like to see additional therapy services added to the program.\", type text}, {\"Therapy staff is flexible and adapts to accommodate HIPsters' needs.\", type text}, {\"Therapy staff communicates effectively regarding therapy goals and schedules.\", type text}, {\"The cost of the therapy program is prohibitive, so my HIPster is not receiving as much therapy as they need.\", type text}, {\"Is there anything you would like to share with the Clinical Services Department?\", type text}, {\"(Optional) HIPster's name:\", type text}, {\"(Optional) Your name:\", type text}, {\"(Optional) Your email address:\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Strongly Agree\",\"Agree\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"Name\", \"Last modified time\", \"My HIPster's Gender:\", \"Type of Therapy Received (may select more than one):\", \"I am satisfied with the therapy services at MP.\", \"My HIPster's daily living skills have improved since starting therapy at MP.\", \"My HIPster's social skills have improved since starting therapy at MP.\", \"My HIPster's communication skills have improved since starting therapy at MP.\", \"My HIPster is more independent since starting therapy services at MP.\", \"The therapy program is addressing the specific needs of my HIPster.\", \"I would like to see additional therapy services added to the program.\", \"Therapy staff is flexible and adapts to accommodate HIPsters' needs.\", \"Therapy staff communicates effectively regarding therapy goals and schedules.\", \"The cost of the therapy program is prohibitive, so my HIPster is not receiving as much therapy as they need.\", \"Is there anything you would like to share with the Clinical Services Department?\", \"(Optional) HIPster's name:\", \"(Optional) Your name:\", \"(Optional) Your email address:\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Strongly Disagree\",\"Disagree\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"Name\", \"Last modified time\", \"My HIPster's Gender:\", \"Type of Therapy Received (may select more than one):\", \"I am satisfied with the therapy services at MP.\", \"My HIPster's daily living skills have improved since starting therapy at MP.\", \"My HIPster's social skills have improved since starting therapy at MP.\", \"My HIPster's communication skills have improved since starting therapy at MP.\", \"My HIPster is more independent since starting therapy services at MP.\", \"The therapy program is addressing the specific needs of my HIPster.\", \"I would like to see additional therapy services added to the program.\", \"Therapy staff is flexible and adapts to accommodate HIPsters' needs.\", \"Therapy staff communicates effectively regarding therapy goals and schedules.\", \"The cost of the therapy program is prohibitive, so my HIPster is not receiving as much therapy as they need.\", \"Is there anything you would like to share with the Clinical Services Department?\", \"(Optional) HIPster's name:\", \"(Optional) Your name:\", \"(Optional) Your email address:\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value1\",{\"Email\", \"Name\", \"Last modified time\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LLL_Hipster",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f76bdeb6-aeb9-4ab9-a924-36f2cc7445e1",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Start time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "614865c3-fe50-43bc-a475-09cb771f2b3e",
            "sourceColumn": "Start time",
            "summarizeBy": "none"
          },
          {
            "name": "Completion time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a0a2d22-b59b-4c29-9850-c524281d3ab0",
            "sourceColumn": "Completion time",
            "summarizeBy": "none"
          },
          {
            "name": "HIPster's Level of Need (LON)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac3053a6-f02a-4124-83ff-a682cd497a9e",
            "sourceColumn": "HIPster's Level of Need (LON)",
            "summarizeBy": "none"
          },
          {
            "name": "HIPster's Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71b5ebe3-de7f-4d91-8724-f7cea5812a9a",
            "sourceColumn": "HIPster's Name",
            "summarizeBy": "none"
          },
          {
            "name": "Gender:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e097792-24a1-4292-88e1-82bb6eb1f68e",
            "sourceColumn": "Gender:",
            "summarizeBy": "none"
          },
          {
            "name": "Program Length",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da43941c-50d7-41c3-bb9b-9796ec57e915",
            "sourceColumn": "Program Length",
            "summarizeBy": "none"
          },
          {
            "name": "AM or PM HIPster",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4b86d5b-a076-4aa7-9596-856d40e9c34e",
            "sourceColumn": "AM or PM HIPster",
            "summarizeBy": "none"
          },
          {
            "name": "How many days per week do you attend MP?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af9d7aae-1b12-464e-8730-552bf37f0215",
            "sourceColumn": "How many days per week do you attend MP?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you like being a HIPster at MP?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72299978-9b3d-4a2f-a0d3-864c5e17e70c",
            "sourceColumn": "Do you like being a HIPster at MP?",
            "summarizeBy": "none"
          },
          {
            "name": "Is MP the place you want to be?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e472181-c10b-495d-865d-3ac6e9b2a31b",
            "sourceColumn": "Is MP the place you want to be?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you learned something new at MP?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93c822e5-a071-47af-b313-42782a712f7c",
            "sourceColumn": "Have you learned something new at MP?",
            "summarizeBy": "none"
          },
          {
            "name": "Do your instructors show care for you?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a54b8663-3260-41db-95dd-d4954dd43dac",
            "sourceColumn": "Do your instructors show care for you?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you made friends with other HIPsters?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7ca7eed-a527-4c8d-b8e4-d45b4e08e0af",
            "sourceColumn": "Have you made friends with other HIPsters?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you pick your own classes?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d5dbaad-09de-4dda-a86a-f8810faf6a4d",
            "sourceColumn": "Do you pick your own classes?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you share what you know?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01b1c48d-a085-4738-9eba-d64905671592",
            "sourceColumn": "Do you share what you know?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you keep trying even when things are hard to do?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77ac025d-9a34-4906-9fb2-746ba655f2c0",
            "sourceColumn": "Do you keep trying even when things are hard to do?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you learn to make good choices at MP?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d657f47-e241-4774-9ca6-203ac2b661ce",
            "sourceColumn": "Do you learn to make good choices at MP?",
            "summarizeBy": "none"
          },
          {
            "name": "Are you excited about your future?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ad6f3d1-f7ac-4a1b-b0e6-3ec9ae67b360",
            "sourceColumn": "Are you excited about your future?",
            "summarizeBy": "none"
          },
          {
            "name": "What I like most about being a HIPster:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc0ba294-ccb9-4bf5-acd4-f17e86ca686c",
            "sourceColumn": "What I like most about being a HIPster:",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "23214ff4-79d0-4fc1-bdbc-5108c8b3879e",
        "partitions": [
          {
            "name": "LLL_Hipster",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://github.com/seancairns14/UTDMyPossibilities/raw/main/Sources/LifeLongLearning/Lifelong%20Learning%C2%A0HIPster%C2%A0Survey(1-197).xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"ID\", Int64.Type}, {\"Start time\", type datetime}, {\"Completion time\", type datetime}, {\"Email\", type text}, {\"Name\", type any}, {\"Last modified time\", type any}, {\"HIPster's Level of Need (LON)\", type text}, {\"HIPster's Name\", type text}, {\"Gender:\", type text}, {\"Program Length\", type text}, {\"AM or PM HIPster\", type text}, {\"How many days per week do you attend MP?\", type text}, {\"Do you like being a HIPster at MP?\", type text}, {\"Is MP the place you want to be?\", type text}, {\"Have you learned something new at MP?\", type text}, {\"Do your instructors show care for you?\", type text}, {\"Have you made friends with other HIPsters?\", type text}, {\"Do you pick your own classes?\", type text}, {\"Do you share what you know?\", type text}, {\"Do you keep trying even when things are hard to do?\", type text}, {\"Do you learn to make good choices at MP?\", type text}, {\"Are you excited about your future?\", type text}, {\"What I like most about being a HIPster:\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Name\", \"Last modified time\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"Sometimes\",\"Yes\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"HIPster's Level of Need (LON)\", \"HIPster's Name\", \"Gender:\", \"Program Length\", \"AM or PM HIPster\", \"How many days per week do you attend MP?\", \"Do you like being a HIPster at MP?\", \"Is MP the place you want to be?\", \"Have you learned something new at MP?\", \"Do your instructors show care for you?\", \"Have you made friends with other HIPsters?\", \"Do you pick your own classes?\", \"Do you share what you know?\", \"Do you keep trying even when things are hard to do?\", \"Do you learn to make good choices at MP?\", \"Are you excited about your future?\", \"What I like most about being a HIPster:\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Replaced Value\",{\"Email\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LLL_Caregiver",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c515eab5-87c7-48f8-b31e-9e02a882bec7",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Start time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eecdd54-f64b-420d-ba7f-30e7dfc11496",
            "sourceColumn": "Start time",
            "summarizeBy": "none"
          },
          {
            "name": "Completion time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "deb9088f-ea69-464e-a702-38d2e3e2b550",
            "sourceColumn": "Completion time",
            "summarizeBy": "none"
          },
          {
            "name": "HIPster's Medicaid Waiver Assigned Level of Need (LON):",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f801e2cc-e05c-4a28-a04e-d0e62e02db76",
            "sourceColumn": "HIPster's Medicaid Waiver Assigned Level of Need (LON):",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster's Gender:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c6133bc-1bc1-49b6-9d75-cd26571b80cf",
            "sourceColumn": "My HIPster's Gender:",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster's Hours of Attendance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a081685d-fbb7-4c3a-816b-81fe9d533b98",
            "sourceColumn": "My HIPster's Hours of Attendance",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPsters Daily Schedule",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0174d956-f52c-4bff-9e38-1c19e1bd72b3",
            "sourceColumn": "My HIPsters Daily Schedule",
            "summarizeBy": "none"
          },
          {
            "name": "The Number of Days a Week My HIPster attends MP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5526533b-fad4-476d-a913-cb4544a354e3",
            "sourceColumn": "The Number of Days a Week My HIPster attends MP",
            "summarizeBy": "none"
          },
          {
            "name": "The Number of Years My HIPster has attended MP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "330347b6-520b-4c10-89f3-f357497e235a",
            "sourceColumn": "The Number of Years My HIPster has attended MP",
            "summarizeBy": "none"
          },
          {
            "name": "MP programs meet the needs of my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c8acbe4-9a7c-48d9-9fb3-1099d420089c",
            "sourceColumn": "MP programs meet the needs of my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "My HIPster has opportunities for community engagement, meaningful activities and events.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a4438a6-4e72-4f49-a9fe-3d2ad96b8e86",
            "sourceColumn": "My HIPster has opportunities for community engagement, meaningful activities and events.",
            "summarizeBy": "none"
          },
          {
            "name": "The MP structure and routine work well for my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f30c2a9a-e666-4c77-a7cd-ca5b52492425",
            "sourceColumn": "The MP structure and routine work well for my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "MP provides a safe and supportive environment for my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b24966e5-b0c5-4d97-b9eb-d0f7ecb98cf2",
            "sourceColumn": "MP provides a safe and supportive environment for my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "MP programs promote socialization, skill-building, and personal growth.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "940b4876-f094-4bbb-9186-466b0d4d9045",
            "sourceColumn": "MP programs promote socialization, skill-building, and personal growth.",
            "summarizeBy": "none"
          },
          {
            "name": "MP staff are knowledgeable about disabilities and have experience working with individuals with diverse needs.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e15943b-719c-4e20-ba93-91961db48741",
            "sourceColumn": "MP staff are knowledgeable about disabilities and have experience working with individuals with diverse needs.",
            "summarizeBy": "none"
          },
          {
            "name": "MP staff is flexible and adapt to accommodate my HIPsters's needs.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89ce25b0-1a21-4bc1-8a7e-73104ba16de3",
            "sourceColumn": "MP staff is flexible and adapt to accommodate my HIPsters's needs.",
            "summarizeBy": "none"
          },
          {
            "name": "MP staff addresses the individual needs of my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93b34e97-d907-4091-8d52-6f2fcbb193a4",
            "sourceColumn": "MP staff addresses the individual needs of my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "MP communicates effectively regarding schedules, events, and activities.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ef4e337-46f3-4152-acd5-efeb45b1563e",
            "sourceColumn": "MP communicates effectively regarding schedules, events, and activities.",
            "summarizeBy": "none"
          },
          {
            "name": "MP programs provide a culture, philosophy, and approach that align with the values and goals my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43c85b3a-38b7-4287-a252-ffb28639bf44",
            "sourceColumn": "MP programs provide a culture, philosophy, and approach that align with the values and goals my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "Please rate the overall quality of programming received in 2023",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d247eabf-bb60-43bf-92c7-f864ac453179",
            "sourceColumn": "Please rate the overall quality of programming received in 2023",
            "summarizeBy": "none"
          },
          {
            "name": "How effectively has My Possibilities addressed your concerns and filled a void in your HIPsters life?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd06ecee-5138-49d7-9e49-3789fb6ae162",
            "sourceColumn": "How effectively has My Possibilities addressed your concerns and filled a void in your HIPsters life?",
            "summarizeBy": "none"
          },
          {
            "name": "How likely are you to recommend My Possibilities?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6425bc2-7e97-491b-ab93-c3bee90d5943",
            "sourceColumn": "How likely are you to recommend My Possibilities?",
            "summarizeBy": "none"
          },
          {
            "name": "The cost of the program limits how often my HIPster can attend.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc88dcae-3a11-4b09-af7a-2f236a967f11",
            "sourceColumn": "The cost of the program limits how often my HIPster can attend.",
            "summarizeBy": "none"
          },
          {
            "name": "Transportation is a challenge for my HIPster to attend MP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3daa0e8-2297-46ae-9bab-1f40ec0a7cdd",
            "sourceColumn": "Transportation is a challenge for my HIPster to attend MP",
            "summarizeBy": "none"
          },
          {
            "name": "How can we improve our programming?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1feb5ea7-9a28-4a35-9b71-d78a0d95280f",
            "sourceColumn": "How can we improve our programming?",
            "summarizeBy": "none"
          },
          {
            "name": "Are there any class topics you would like to see introduced to our programming?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8aef4a2-4056-4287-b616-6cb5aa4c996b",
            "sourceColumn": "Are there any class topics you would like to see introduced to our programming?",
            "summarizeBy": "none"
          },
          {
            "name": "How can we improve our our administrative processes? (billing, communications, events, etc.?)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "783e0405-30e4-4d67-b5b2-6bae068e93cc",
            "sourceColumn": "How can we improve our our administrative processes? (billing, communications, events, etc.?)",
            "summarizeBy": "none"
          },
          {
            "name": "What do you believe your HIPsters life would be like without the support and services provided by My Possibilities?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3db7284c-f3eb-4422-aede-cef585fc52c4",
            "sourceColumn": "What do you believe your HIPsters life would be like without the support and services provided by My Possibilities?",
            "summarizeBy": "none"
          },
          {
            "name": "Is there any additional information you would like to share with the leadership team?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83a22bb2-ff8e-4ea3-83c8-2f97378f39ae",
            "sourceColumn": "Is there any additional information you would like to share with the leadership team?",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) HIPster's name:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5554c4b-f84d-4697-8d5b-d80cce1fa8f4",
            "sourceColumn": "(Optional) HIPster's name:",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) Your name:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "276e50b9-6c23-4df2-8451-adb8add24070",
            "sourceColumn": "(Optional) Your name:",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) Your email address:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9f03f8a-8a3b-4c8d-8686-f25b854d9557",
            "sourceColumn": "(Optional) Your email address:",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "54b40d05-53d0-423c-98ea-3fe2a422f558",
        "partitions": [
          {
            "name": "LLL_Caregiver",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://github.com/seancairns14/UTDMyPossibilities/raw/main/Sources/LifeLongLearning/Lifelong%20Learning%C2%A0Caregiver%C2%A0Survey(1-104).xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"ID\", Int64.Type}, {\"Start time\", type datetime}, {\"Completion time\", type datetime}, {\"Email\", type text}, {\"Name\", type any}, {\"Last modified time\", type any}, {\"HIPster's Medicaid Waiver Assigned Level of Need (LON):\", type text}, {\"My HIPster's Gender:\", type text}, {\"My HIPster's Hours of Attendance\", type text}, {\"My HIPsters Daily Schedule\", type text}, {\"The Number of Days a Week My HIPster attends MP\", Int64.Type}, {\"The Number of Years My HIPster has attended MP\", type text}, {\"MP programs meet the needs of my HIPster.\", type text}, {\"My HIPster has opportunities for community engagement, meaningful activities and events.\", type text}, {\"The MP structure and routine work well for my HIPster.\", type text}, {\"MP provides a safe and supportive environment for my HIPster.\", type text}, {\"MP programs promote socialization, skill-building, and personal growth.\", type text}, {\"MP staff are knowledgeable about disabilities and have experience working with individuals with diverse needs.\", type text}, {\"MP staff is flexible and adapt to accommodate my HIPsters's needs.\", type text}, {\"MP staff addresses the individual needs of my HIPster.\", type text}, {\"MP communicates effectively regarding schedules, events, and activities.\", type text}, {\"MP programs provide a culture, philosophy, and approach that align with the values and goals my HIPster.\", type text}, {\"Please rate the overall quality of programming received in 2023\", Int64.Type}, {\"How effectively has My Possibilities addressed your concerns and filled a void in your HIPsters life?\", Int64.Type}, {\"How likely are you to recommend My Possibilities?\", Int64.Type}, {\"The cost of the program limits how often my HIPster can attend.\", type text}, {\"Transportation is a challenge for my HIPster to attend MP\", type text}, {\"How can we improve our programming?\", type text}, {\"Are there any class topics you would like to see introduced to our programming?\", type text}, {\"How can we improve our our administrative processes? (billing, communications, events, etc.?)\", type text}, {\"What do you believe your HIPsters life would be like without the support and services provided by My Possibilities?\", type text}, {\"Is there any additional information you would like to share with the leadership team?\", type text}, {\"(Optional) HIPster's name:\", type text}, {\"(Optional) Your name:\", type text}, {\"(Optional) Your email address:\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Name\", \"Last modified time\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"Strongly Agree\",\"Agree\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"HIPster's Medicaid Waiver Assigned Level of Need (LON):\", \"My HIPster's Gender:\", \"My HIPster's Hours of Attendance\", \"My HIPsters Daily Schedule\", \"The Number of Days a Week My HIPster attends MP\", \"The Number of Years My HIPster has attended MP\", \"MP programs meet the needs of my HIPster.\", \"My HIPster has opportunities for community engagement, meaningful activities and events.\", \"The MP structure and routine work well for my HIPster.\", \"MP provides a safe and supportive environment for my HIPster.\", \"MP programs promote socialization, skill-building, and personal growth.\", \"MP staff are knowledgeable about disabilities and have experience working with individuals with diverse needs.\", \"MP staff is flexible and adapt to accommodate my HIPsters's needs.\", \"MP staff addresses the individual needs of my HIPster.\", \"MP communicates effectively regarding schedules, events, and activities.\", \"MP programs provide a culture, philosophy, and approach that align with the values and goals my HIPster.\", \"Please rate the overall quality of programming received in 2023\", \"How effectively has My Possibilities addressed your concerns and filled a void in your HIPsters life?\", \"How likely are you to recommend My Possibilities?\", \"The cost of the program limits how often my HIPster can attend.\", \"Transportation is a challenge for my HIPster to attend MP\", \"How can we improve our programming?\", \"Are there any class topics you would like to see introduced to our programming?\", \"How can we improve our our administrative processes? (billing, communications, events, etc.?)\", \"What do you believe your HIPsters life would be like without the support and services provided by My Possibilities?\", \"Is there any additional information you would like to share with the leadership team?\", \"(Optional) HIPster's name:\", \"(Optional) Your name:\", \"(Optional) Your email address:\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Strongly Disagree\",\"Disagree\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"HIPster's Medicaid Waiver Assigned Level of Need (LON):\", \"My HIPster's Gender:\", \"My HIPster's Hours of Attendance\", \"My HIPsters Daily Schedule\", \"The Number of Days a Week My HIPster attends MP\", \"The Number of Years My HIPster has attended MP\", \"MP programs meet the needs of my HIPster.\", \"My HIPster has opportunities for community engagement, meaningful activities and events.\", \"The MP structure and routine work well for my HIPster.\", \"MP provides a safe and supportive environment for my HIPster.\", \"MP programs promote socialization, skill-building, and personal growth.\", \"MP staff are knowledgeable about disabilities and have experience working with individuals with diverse needs.\", \"MP staff is flexible and adapt to accommodate my HIPsters's needs.\", \"MP staff addresses the individual needs of my HIPster.\", \"MP communicates effectively regarding schedules, events, and activities.\", \"MP programs provide a culture, philosophy, and approach that align with the values and goals my HIPster.\", \"Please rate the overall quality of programming received in 2023\", \"How effectively has My Possibilities addressed your concerns and filled a void in your HIPsters life?\", \"How likely are you to recommend My Possibilities?\", \"The cost of the program limits how often my HIPster can attend.\", \"Transportation is a challenge for my HIPster to attend MP\", \"How can we improve our programming?\", \"Are there any class topics you would like to see introduced to our programming?\", \"How can we improve our our administrative processes? (billing, communications, events, etc.?)\", \"What do you believe your HIPsters life would be like without the support and services provided by My Possibilities?\", \"Is there any additional information you would like to share with the leadership team?\", \"(Optional) HIPster's name:\", \"(Optional) Your name:\", \"(Optional) Your email address:\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Replaced Value1\",{\"Email\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Online_Caregiver",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51672a7e-ebd5-410f-8619-210bb3ac02bf",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Start time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9c33f6d-5404-4dfe-a6d1-779da4a255f3",
            "sourceColumn": "Start time",
            "summarizeBy": "none"
          },
          {
            "name": "Completion time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42b1e4a0-ceec-4eb0-8184-59e7b326f4af",
            "sourceColumn": "Completion time",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94979045-b669-4bb2-819a-24c83e7e5e8b",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "HIPster's Medicaid Waiver Assigned Level of Need (LON):",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "deb580dd-8242-49f8-bf69-7be11b5fa20d",
            "sourceColumn": "HIPster's Medicaid Waiver Assigned Level of Need (LON):",
            "summarizeBy": "none"
          },
          {
            "name": "HIPster's Gender:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a06c6b4-7315-4b23-9011-281017f27526",
            "sourceColumn": "HIPster's Gender:",
            "summarizeBy": "none"
          },
          {
            "name": "Number of Days a Week HIPster attends MP Online Classes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ec4a2ea-99b2-4a05-b2ba-14eca91f8ec1",
            "sourceColumn": "Number of Days a Week HIPster attends MP Online Classes",
            "summarizeBy": "none"
          },
          {
            "name": "What year did your HIPster begin MP Online?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f0a8a99-370d-4aee-b374-9a36e21a2936",
            "sourceColumn": "What year did your HIPster begin MP Online?",
            "summarizeBy": "none"
          },
          {
            "name": "MP Online meet the needs of my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b0cffd8-80f9-411f-bb46-ab31ff296c49",
            "sourceColumn": "MP Online meet the needs of my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "MP Online provides a safe and supportive environment for my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60e7f111-86b9-4d03-a25c-67ab8abedc76",
            "sourceColumn": "MP Online provides a safe and supportive environment for my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "MP Online promote socialization, skill-building, and personal growth.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9942c68f-f289-4e2d-a492-e64201cb929e",
            "sourceColumn": "MP Online promote socialization, skill-building, and personal growth.",
            "summarizeBy": "none"
          },
          {
            "name": "MP Online Instructor is knowledgeable about disabilities and has experience working with individuals with diverse needs.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b429558-1339-4729-a41c-7c977e228105",
            "sourceColumn": "MP Online Instructor is knowledgeable about disabilities and has experience working with individuals with diverse needs.",
            "summarizeBy": "none"
          },
          {
            "name": "The MP Online structure and routine work well for my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "389f605c-5213-43fa-b125-8fa0d1187ff3",
            "sourceColumn": "The MP Online structure and routine work well for my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "The MP Online staff addresses the individual needs of my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0ec8d43-a20b-4a0e-a4ea-e701ee2b1814",
            "sourceColumn": "The MP Online staff addresses the individual needs of my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "The MP Online program is flexible and accommodates my HIPsters's needs.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "293fa3f2-6b48-4a2a-a6e5-971cd31ccf58",
            "sourceColumn": "The MP Online program is flexible and accommodates my HIPsters's needs.",
            "summarizeBy": "none"
          },
          {
            "name": "The MP Online program provides a culture, philosophy, and approach that align with the values and goals my HIPster.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03c9e7fb-37a0-43b2-88ff-d75463f34357",
            "sourceColumn": "The MP Online program provides a culture, philosophy, and approach that align with the values and goals my HIPster.",
            "summarizeBy": "none"
          },
          {
            "name": "Transportation is a challenge for my HIPster to attend MP in person",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51124202-f590-467d-8e5a-4b25e387d470",
            "sourceColumn": "Transportation is a challenge for my HIPster to attend MP in person",
            "summarizeBy": "none"
          },
          {
            "name": "The cost of the program limits how often my HIPster can attend.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "728eefe8-a670-4878-8d46-8782ba2f5d44",
            "sourceColumn": "The cost of the program limits how often my HIPster can attend.",
            "summarizeBy": "none"
          },
          {
            "name": "Would you like to see any additional programming such as a movie night or opportunities for socialization outside normal MP Online hours?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11f2cacb-94f7-4ac8-949d-ce81cf2ecb8b",
            "sourceColumn": "Would you like to see any additional programming such as a movie night or opportunities for socialization outside normal MP Online hours?",
            "summarizeBy": "none"
          },
          {
            "name": "Is there anything you would like to share with the MP Leadership Team?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec7a2fd1-8ec6-4048-9149-9769fd86b3a4",
            "sourceColumn": "Is there anything you would like to share with the MP Leadership Team?",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) HIPster's name:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4588e265-47c2-4479-85aa-2ac9597a8552",
            "sourceColumn": "(Optional) HIPster's name:",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) Your name:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccc864aa-7455-40fa-a52d-8f30e3073d0f",
            "sourceColumn": "(Optional) Your name:",
            "summarizeBy": "none"
          },
          {
            "name": "(Optional) Your email address:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74fee95e-0429-459f-9fd2-581d01e44013",
            "sourceColumn": "(Optional) Your email address:",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c0bb47ad-4706-4334-8101-877d90f0fc55",
        "partitions": [
          {
            "name": "Online_Caregiver",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://github.com/seancairns14/UTDMyPossibilities/raw/main/Sources/Online/Online%C2%A0Caregiver%C2%A0Survey(1-12).xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"ID\", Int64.Type}, {\"Start time\", type datetime}, {\"Completion time\", type datetime}, {\"Email\", type text}, {\"Name\", type any}, {\"Last modified time\", type any}, {\"HIPster's Medicaid Waiver Assigned Level of Need (LON):\", type text}, {\"HIPster's Gender:\", type text}, {\"Number of Days a Week HIPster attends MP Online Classes\", Int64.Type}, {\"What year did your HIPster begin MP Online?\", Int64.Type}, {\"MP Online meet the needs of my HIPster.\", type text}, {\"MP Online provides a safe and supportive environment for my HIPster.\", type text}, {\"MP Online promote socialization, skill-building, and personal growth.\", type text}, {\"MP Online Instructor is knowledgeable about disabilities and has experience working with individuals with diverse needs.\", type text}, {\"The MP Online structure and routine work well for my HIPster.\", type text}, {\"The MP Online staff addresses the individual needs of my HIPster.\", type text}, {\"The MP Online program is flexible and accommodates my HIPsters's needs.\", type text}, {\"The MP Online program provides a culture, philosophy, and approach that align with the values and goals my HIPster.\", type text}, {\"Transportation is a challenge for my HIPster to attend MP in person\", type text}, {\"The cost of the program limits how often my HIPster can attend.\", type text}, {\"Would you like to see any additional programming such as a movie night or opportunities for socialization outside normal MP Online hours?\", type text}, {\"Is there anything you would like to share with the MP Leadership Team?\", type text}, {\"(Optional) HIPster's name:\", type text}, {\"(Optional) Your name:\", type text}, {\"(Optional) Your email address:\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Strongly Agree\",\"Agree\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"Name\", \"Last modified time\", \"HIPster's Medicaid Waiver Assigned Level of Need (LON):\", \"HIPster's Gender:\", \"Number of Days a Week HIPster attends MP Online Classes\", \"What year did your HIPster begin MP Online?\", \"MP Online meet the needs of my HIPster.\", \"MP Online provides a safe and supportive environment for my HIPster.\", \"MP Online promote socialization, skill-building, and personal growth.\", \"MP Online Instructor is knowledgeable about disabilities and has experience working with individuals with diverse needs.\", \"The MP Online structure and routine work well for my HIPster.\", \"The MP Online staff addresses the individual needs of my HIPster.\", \"The MP Online program is flexible and accommodates my HIPsters's needs.\", \"The MP Online program provides a culture, philosophy, and approach that align with the values and goals my HIPster.\", \"Transportation is a challenge for my HIPster to attend MP in person\", \"The cost of the program limits how often my HIPster can attend.\", \"Would you like to see any additional programming such as a movie night or opportunities for socialization outside normal MP Online hours?\", \"Is there anything you would like to share with the MP Leadership Team?\", \"(Optional) HIPster's name:\", \"(Optional) Your name:\", \"(Optional) Your email address:\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Strongly Disagree\",\"Disagree\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"Name\", \"Last modified time\", \"HIPster's Medicaid Waiver Assigned Level of Need (LON):\", \"HIPster's Gender:\", \"Number of Days a Week HIPster attends MP Online Classes\", \"What year did your HIPster begin MP Online?\", \"MP Online meet the needs of my HIPster.\", \"MP Online provides a safe and supportive environment for my HIPster.\", \"MP Online promote socialization, skill-building, and personal growth.\", \"MP Online Instructor is knowledgeable about disabilities and has experience working with individuals with diverse needs.\", \"The MP Online structure and routine work well for my HIPster.\", \"The MP Online staff addresses the individual needs of my HIPster.\", \"The MP Online program is flexible and accommodates my HIPsters's needs.\", \"The MP Online program provides a culture, philosophy, and approach that align with the values and goals my HIPster.\", \"Transportation is a challenge for my HIPster to attend MP in person\", \"The cost of the program limits how often my HIPster can attend.\", \"Would you like to see any additional programming such as a movie night or opportunities for socialization outside normal MP Online hours?\", \"Is there anything you would like to share with the MP Leadership Team?\", \"(Optional) HIPster's name:\", \"(Optional) Your name:\", \"(Optional) Your email address:\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value1\",{\"Name\", \"Last modified time\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Online_HIPster",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a2f833a-e6cf-44b1-b811-e8569c8166bb",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Start time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb200375-8f51-45be-99fb-5d91fdc419da",
            "sourceColumn": "Start time",
            "summarizeBy": "none"
          },
          {
            "name": "Completion time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50ce3558-2ed7-4107-b409-2655c6b66072",
            "sourceColumn": "Completion time",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84c53fe6-9653-4a63-834b-9636ada5c9b2",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "HIPster's Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f59e6fad-1f51-4033-95e3-810a427b773d",
            "sourceColumn": "HIPster's Name",
            "summarizeBy": "none"
          },
          {
            "name": "Gender:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8473b077-5e22-4c9b-b6a8-473d071fc850",
            "sourceColumn": "Gender:",
            "summarizeBy": "none"
          },
          {
            "name": "How do you attend My Possibilities?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54dafa7a-059c-4c97-b7c2-f0ee8d9f20ae",
            "sourceColumn": "How do you attend My Possibilities?",
            "summarizeBy": "none"
          },
          {
            "name": "How many days per week do you attend MP Online?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70a90c62-de75-43aa-ad18-69a3cfc999e2",
            "sourceColumn": "How many days per week do you attend MP Online?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you like being a HIPster at MP?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41ff49a3-bd56-4527-b409-1a3ee065e542",
            "sourceColumn": "Do you like being a HIPster at MP?",
            "summarizeBy": "none"
          },
          {
            "name": "Is MP Online the place you want to be?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3002eb31-2721-4e7d-aa5a-7286d1185076",
            "sourceColumn": "Is MP Online the place you want to be?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you learned something new at MP Online?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7610bd7d-ff2a-4a99-ba46-7efa2d5ecf07",
            "sourceColumn": "Have you learned something new at MP Online?",
            "summarizeBy": "none"
          },
          {
            "name": "Does your instructor care about you?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c9b212f-b65f-4fb2-ae6b-1a644e2ec46c",
            "sourceColumn": "Does your instructor care about you?",
            "summarizeBy": "none"
          },
          {
            "name": "Have you made friends with other HIPsters?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9fc227f-2de2-45fc-9375-b28ddad61905",
            "sourceColumn": "Have you made friends with other HIPsters?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you pick your own classes?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19c37962-2abb-4c81-8ccc-0272f0ea2d4f",
            "sourceColumn": "Do you pick your own classes?",
            "summarizeBy": "none"
          },
          {
            "name": "Can you share what you know with your class?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a44f1f01-f419-440b-926b-92c9a6d67abf",
            "sourceColumn": "Can you share what you know with your class?",
            "summarizeBy": "none"
          },
          {
            "name": "Do you keep trying even when things are hard to do?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b14f6431-56df-41ee-82d9-bb364a576cb0",
            "sourceColumn": "Do you keep trying even when things are hard to do?",
            "summarizeBy": "none"
          },
          {
            "name": "Does MP Online help you learn to make good choices?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc1101ba-61b4-430f-8bad-1be9f33e719c",
            "sourceColumn": "Does MP Online help you learn to make good choices?",
            "summarizeBy": "none"
          },
          {
            "name": "Are you excited about your future?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e2f1933-9ff4-4158-af3e-b7c55e0a793c",
            "sourceColumn": "Are you excited about your future?",
            "summarizeBy": "none"
          },
          {
            "name": "What do you like best about being a HIPster:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13e8f278-33a7-4f89-b64a-64df2a346092",
            "sourceColumn": "What do you like best about being a HIPster:",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b7df026c-db39-4a0c-ac0f-1ac1ec7b7028",
        "partitions": [
          {
            "name": "Online_HIPster",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://github.com/seancairns14/UTDMyPossibilities/raw/main/Sources/Online/Online%C2%A0HIPster%C2%A0Survey(1-14).xlsx\"), null, true),",
                "    Table1_Table = Source{[Item=\"Table1\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Table1_Table,{{\"ID\", Int64.Type}, {\"Start time\", type datetime}, {\"Completion time\", type datetime}, {\"Email\", type text}, {\"Name\", type any}, {\"Last modified time\", type any}, {\"HIPster's Name\", type text}, {\"Gender:\", type text}, {\"How do you attend My Possibilities?\", type text}, {\"How many days per week do you attend MP Online?\", Int64.Type}, {\"Do you like being a HIPster at MP?\", type text}, {\"Is MP Online the place you want to be?\", type text}, {\"Have you learned something new at MP Online?\", type text}, {\"Does your instructor care about you?\", type text}, {\"Have you made friends with other HIPsters?\", type text}, {\"Do you pick your own classes?\", type text}, {\"Can you share what you know with your class?\", type text}, {\"Do you keep trying even when things are hard to do?\", type text}, {\"Does MP Online help you learn to make good choices?\", type text}, {\"Are you excited about your future?\", type text}, {\"What do you like best about being a HIPster:\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Sometimes\",\"Yes\",Replacer.ReplaceValue,{\"ID\", \"Start time\", \"Completion time\", \"Email\", \"Name\", \"Last modified time\", \"HIPster's Name\", \"Gender:\", \"How do you attend My Possibilities?\", \"How many days per week do you attend MP Online?\", \"Do you like being a HIPster at MP?\", \"Is MP Online the place you want to be?\", \"Have you learned something new at MP Online?\", \"Does your instructor care about you?\", \"Have you made friends with other HIPsters?\", \"Do you pick your own classes?\", \"Can you share what you know with your class?\", \"Do you keep trying even when things are hard to do?\", \"Does MP Online help you learn to make good choices?\", \"Are you excited about your future?\", \"What do you like best about being a HIPster:\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value\",{\"Name\", \"Last modified time\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}